#!/bin/sh

# Run the Mogwai installed-tests which do not require root privileges.

# Copyright © 2017, 2018 Endless Mobile, Inc.
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

set -e
exec 2>&1

exec gnome-desktop-testing-runner \
	libmogwai-helper-1 \
	libmogwai-schedule-1 \
	libmogwai-schedule-client-0 \
	libmogwai-tariff-0 \
	mogwai-schedule-client-1 \
	mogwai-scheduled-1 \
	--
